import type { Metadata } from 'next';
import { Lato } from 'next/font/google';
import './globals.css';

const lato = Lato({ weight: ['100', '300', '700'], subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  children: React.ReactNode;
  parallel: React.ReactNode;
};

export default function RootLayout({ children, parallel }: Props) {
  return (
    <html lang='en'>
      <body className={lato.className}>
        {children} {parallel}{' '}
      </body>
    </html>
  );
}
